#!/usr/bin/env bash
set -Eeuo pipefail

echo "======================================="
echo "Trinket OSS Minimal Hyper-V Docker Setup"
echo "======================================="

INSTALL_DIR="${INSTALL_DIR:-/opt/trinket-oss}"
#TRINKET_REPO="${TRINKET_REPO:-https://github.com/trinketapp/trinket-oss.git}"
PRIMARY_REPO="https://github.com/marc-hundley-oasisuk-org/trinket-oss.git"
FALLBACK_REPO="https://github.com/trinketapp/trinket-oss.git"

COMPOSE_FILE="${INSTALL_DIR}/docker-compose.minimal.yml"

# For your own fork, run:
# sudo TRINKET_REPO="https://github.com/marc-hundley-oasisuk-org/trinket-oss.git" ./setup-trinket-oss.sh

log() {
  echo ""
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

need_root() {
  if [ "${EUID}" -ne 0 ]; then
    die "Please run this script with sudo."
  fi
}

detect_compose() {
  if docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
  else
    die "Docker Compose is not installed."
  fi

  echo "Using Compose command: ${COMPOSE_CMD}"
}

install_docker() {
  log "Installing Docker and Docker Compose if required"

  apt-get update -y

  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    docker.io \
    docker-compose \
    git \
    curl \
    openssl

  systemctl enable docker
  systemctl start docker

  docker --version
  detect_compose
}


clone_or_update_repo() {
  log "Preparing repository at ${INSTALL_DIR}"

  if [ -d "${INSTALL_DIR}/.git" ]; then
    log "Repository already exists, skipping clone"
    cd "${INSTALL_DIR}"
    return
  fi

  mkdir -p "$(dirname "${INSTALL_DIR}")"

  log "Testing access to primary repo..."
  if git ls-remote "${PRIMARY_REPO}" &>/dev/null; then
    log "✅ Primary repo reachable, cloning..."
    git clone "${PRIMARY_REPO}" "${INSTALL_DIR}"
  else
    log "⚠️ Primary repo not reachable, falling back to upstream..."

    if git ls-remote "${FALLBACK_REPO}" &>/dev/null; then
      log "✅ Upstream repo reachable, cloning..."
      git clone "${FALLBACK_REPO}" "${INSTALL_DIR}"
    else
      die "❌ Failed to access both repositories"
    fi
  fi

  cd "${INSTALL_DIR}"

  # Add upstream for tracking (safe if already exists)
  git remote add upstream "${FALLBACK_REPO}" 2>/dev/null || true
}

create_local_config() {
  log "Creating minimal local.yaml"

  mkdir -p "${INSTALL_DIR}/config"

  SESSION_SECRET="$(openssl rand -base64 48 | tr -d '\n')"

  VM_IP=$(hostname -I | awk '{print $1}')
  TRINKET_PROTOCOL="${TRINKET_PROTOCOL:-http}"
  TRINKET_HOSTNAME="${TRINKET_HOSTNAME:-${VM_IP}}"
  TRINKET_PORT="${TRINKET_PORT:-3000}"

  MICROSOFT_SSO_ENABLED="${MICROSOFT_SSO_ENABLED:-false}"
  MICROSOFT_TENANT_ID="${MICROSOFT_TENANT_ID:-}"
  MICROSOFT_CLIENT_ID="${MICROSOFT_CLIENT_ID:-}"
  MICROSOFT_CLIENT_SECRET="${MICROSOFT_CLIENT_SECRET:-}"
  MICROSOFT_CALLBACK_URL="${MICROSOFT_CALLBACK_URL:-${TRINKET_PROTOCOL}://${TRINKET_HOSTNAME}:${TRINKET_PORT}/auth/microsoft/callback}"
  MICROSOFT_AUTO_CREATE_USERS="${MICROSOFT_AUTO_CREATE_USERS:-true}"
  MICROSOFT_ALLOWED_DOMAINS="${MICROSOFT_ALLOWED_DOMAINS:-}"

  if [ -z "${MICROSOFT_ALLOWED_DOMAINS}" ]; then
    MICROSOFT_ALLOWED_DOMAINS_BLOCK="      allowedDomains: []"
  else
    MICROSOFT_ALLOWED_DOMAINS_BLOCK="      allowedDomains:"
    IFS=',' read -ra DOMAIN_LIST <<< "${MICROSOFT_ALLOWED_DOMAINS}"
    for DOMAIN in "${DOMAIN_LIST[@]}"; do
      DOMAIN="$(echo "${DOMAIN}" | xargs)"
      if [ -n "${DOMAIN}" ]; then
        MICROSOFT_ALLOWED_DOMAINS_BLOCK="${MICROSOFT_ALLOWED_DOMAINS_BLOCK}
        - '${DOMAIN}'"
      fi
    done
  fi

  cat > "${INSTALL_DIR}/config/local.yaml" <<EOF
# Generated by setup-trinket-oss.sh
# Minimal Hyper-V Docker test configuration.
# Redis is intentionally not configured.

app:
  url:
    hostname: ${TRINKET_HOSTNAME}
    port: ${TRINKET_PORT}
    protocol: ${TRINKET_PROTOCOL}
  basePath: "/"

  plugins:
    session:
      cookieOptions:
        password: "${SESSION_SECRET}"
        isSecure: false
  sitename: 'OCL Computer Science'
  supportemail: 'servicedesk@oasisuk.org'
  #logo: '/img/my-logo.png'
  embed:
    skulpt:
      local: true
      min: true

  auth:
    microsoft:
      enabled: ${MICROSOFT_SSO_ENABLED}
      tenantId: '${MICROSOFT_TENANT_ID}'
      clientID: '${MICROSOFT_CLIENT_ID}'
      clientSecret: '${MICROSOFT_CLIENT_SECRET}'
      callbackURL: '${MICROSOFT_CALLBACK_URL}'
${MICROSOFT_ALLOWED_DOMAINS_BLOCK}
      autoCreateUsers: ${MICROSOFT_AUTO_CREATE_USERS}

db:
  mongo:
      host: 127.0.0.1
      port: 27017
      database: trinket

  #Redis is optional - sessions work without it
  redis:
    enabled: false

features:
  trinkets:
    python: true
    html: true
    python3: false

  assets: false
  courses: true
  accessibilityToggle: false

cdn:
  enabled: false

assets:
  useCDN: false

queue:
  enabled: false

exports:
  enabled: false

aws:
  buckets:
    cdn:
      host: ''

    vendorassets:
      host: ''

    skulpt:
      host: ''

  enabled: false
EOF

  chmod 644 "${INSTALL_DIR}/config/local.yaml"
}

create_minimal_compose() {
  log "Creating minimal Docker Compose file"

  cat > "${COMPOSE_FILE}" <<EOF
version: "3.8"

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trinket/app:latest
    container_name: trinket
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ""
    volumes:
      - ./config/local.yaml:/usr/local/node/trinket/config/local.yaml:ro

volumes:
  mongodb_data:
EOF
}

clean_previous_stacks() {
  log "Cleaning previous Trinket containers"

  cd "${INSTALL_DIR}"

  # Stop minimal stack.
  ${COMPOSE_CMD} -f "${COMPOSE_FILE}" down || true

  # Stop upstream/default stack if it was accidentally used.
  if [ -f "${INSTALL_DIR}/docker-compose.yml" ]; then
    ${COMPOSE_CMD} -f "${INSTALL_DIR}/docker-compose.yml" down || true
  fi

  docker rm -f trinket mongodb redis 2>/dev/null || true
}

build_and_start() {
  log "Building and starting minimal stack"

  cd "${INSTALL_DIR}"

  ${COMPOSE_CMD} -f "${COMPOSE_FILE}" build --no-cache app
  ${COMPOSE_CMD} -f "${COMPOSE_FILE}" up -d
}

validate_runtime() {
  log "Validating runtime"

  echo ""
  echo "Docker containers:"
  docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

  echo ""
  echo "Checking Trinket logs:"
  docker logs trinket --tail=80 || true

  echo ""
  echo "Testing local HTTP response from VM..."

  for i in $(seq 1 30); do
    if curl -fsS --max-time 5 http://localhost:3000 >/tmp/trinket-http-test.html; then
      echo "✅ Trinket responded successfully on http://localhost:3000"
      return 0
    fi

    if ! docker ps --format '{{.Names}}' | grep -qx trinket; then
      echo "❌ Trinket container is not running."
      docker logs trinket --tail=150 || true
      exit 1
    fi

    sleep 2
  done

  echo "❌ Trinket did not return a successful HTTP response."
  echo ""
  echo "Useful diagnostics:"
  echo "  sudo docker logs trinket --tail=150"
  echo "  sudo docker ps"
  echo "  sudo ss -lntp | grep ':3000\\|:27017'"
  exit 1
}

print_summary() {
  VM_IP="$(hostname -I | awk '{print $1}')"

  echo ""
  echo "======================================="
  echo "✅ Trinket OSS minimal setup complete"
  echo "======================================="
  echo ""
  echo "Try from inside the VM:"
  echo "  curl http://localhost:3000"
  echo ""
  echo "Try from the Hyper-V host browser:"
  echo "  http://${VM_IP}:3000"
  echo ""
  echo "Useful commands:"
  echo "  cd ${INSTALL_DIR}"
  echo "  sudo ${COMPOSE_CMD} -f ${COMPOSE_FILE} logs -f"
  echo "  sudo ${COMPOSE_CMD} -f ${COMPOSE_FILE} restart"
  echo "  sudo docker logs trinket --tail=100"
  echo ""
  echo "Important:"
  echo "  Always use the minimal compose file:"
  echo "  sudo ${COMPOSE_CMD} -f ${COMPOSE_FILE} up -d"
  echo ""
  echo "Do not use plain:"
  echo "  sudo docker-compose up -d"
  echo ""
  echo "Plain docker-compose uses the upstream docker-compose.yml and will start Redis again."
  echo ""
}

main() {
  need_root
  install_docker
  clone_or_update_repo
  create_local_config
  create_minimal_compose
  clean_previous_stacks
  build_and_start
  validate_runtime
  print_summary
}

main "$@"
